app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/', 'CatalogsController@index');
    Route::get('/r', 'CatalogsController@r');
    Route::get('catalogs', 'CatalogsController@catalogs');
    Route::get('search', 'CatalogsController@search');
    Route::get('details/{id}', 'CatalogsController@details');
    Route::get('mail', 'UsersController@mail');
    Route::get('/home', 'HomeController@index');
    Route::resource('/customers', 'CustomersController', ['only' => [
        'index', 'show', 'update'
    ]]);
    
    Route::resource('categories', 'CategoriesController');
    Route::resource('products', 'ProductsController');
    Route::resource('users', 'UsersController');
    Route::resource('orders', 'OrdersController', ['only' => [
        'index', 'edit', 'update'
    ]]);

    Route::post('cart', 'CartController@addProduct');
    Route::get('cart', 'CartController@show');
    Route::delete('cart/{product_id}', 'CartController@removeProduct');
    Route::put('cart/{product_id}', 'CartController@changeQuantity');

    Route::get('checkout/login', 'CheckoutController@login');
    Route::post('checkout/login', 'CheckoutController@postLogin');
    Route::get('checkout/address', 'CheckoutController@address');
    Route::post('checkout/address', 'CheckoutController@postAddress');
    Route::get('checkout/payment', 'CheckoutController@payment');
    Route::post('checkout/payment', 'CheckoutController@postPayment');
    Route::get('checkout/success', 'CheckoutController@success');
});


Route::group(['middleware' => 'api'], function () {
    Route::get('address/regencies', 'AddressController@regencies');
});

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    protected $fillable = ['id', 'user_id', 'address_id', 'bank', 'sender',
        'status', 'total_payment', 'confirmation'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function details()
    {
        return $this->hasMany('App\OrderDetail');
    }

    public function address()
    {
        return $this->belongsTo('App\Address');
    }

    public function refreshTotalPayment()
    {
        $total_payment = 0;
        foreach($this->details as $detail) {
            $total_payment += $detail->total_price;
        }
        $this->total_payment = $total_payment;
        $this->save();
    }
    
    public function getPaddedIdAttribute()
    {
        return str_pad($this->id, 6, 0, STR_PAD_LEFT);
    }
    
    public static function statusList()
    {
        return [
            'waiting-payment' => 'Menunggu Pembayaran',
            'packaging' => 'Order disiapkan',
            'sent' => 'Paket dikirim',
            'finished' => 'Paket diterima'
        ];
    }

    public static function allowedStatus()
    {
        return array_keys(static::statusList());
    }

    public function getHumanStatusAttribute()
    {
        return static::statusList()[$this->status];
    }
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use File;

class CustomersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:customer');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = auth()->user()->orders()->get();

        return view('customer.view-orders')->with(compact('orders'));
        // return  auth()->user()->orders()->findOrFail($id);
    }

    public function show($id)
    {
        $orders = auth()->user()->orders()
            ->where('id', $id)->get();
        return view('customer.detail-orders')->with(compact('orders'));
    }

    public function update(Request $request, $id)
    {
        $customer = auth()->user()->orders()->findOrFail($id);
        // return $customer;
        $this->validate($request, [
            'confirmation' => 'mimes:jpeg,png|max:10240'
        ]);
        // $data = array();
        if ($request->hasFile('confirmation')) {
            $data['confirmation'] = $this->savePhoto($request->file('confirmation'));
            if ($customer->confirmation !== '') 
                    $this->deletePhoto($customer->confirmation);
        }

        $customer->update($data);

        \Flash::success('Berhasil di update.');
        return redirect()->route('customers.index');
    }

    protected function savePhoto(UploadedFile $photo)
    {
        $fileName = str_random(40) . '.' . $photo->guessClientExtension();
        $destinationPath = public_path() . DIRECTORY_SEPARATOR . 'img/confirmation';
        $photo->move($destinationPath, $fileName);
        return $fileName;
    }

    public function deletePhoto($filename)
    {
        $path = public_path() . DIRECTORY_SEPARATOR . 'img/confirmation'
            . DIRECTORY_SEPARATOR . $filename;
        return File::delete($path);
    }
}

resources/views/customer/detail-orders.blade.php
@extends('layouts.shop')

@section('content')
  <div class="container">
    <div class="row" style="margin-top: 50px;font-size: 12pt">
      <div class="col-md-12">
          @forelse($orders as $order)
          <h3>Detail Order {{ $order->padded_id }}</h3><br>
          <table class="table table-bordered table-condensed">
            <thead>
              <tr>
                <th>Tanggal Order</th>
                <th>Pembayaran</th>
                <th>Detail</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>{{ $order->created_at }}</td>
                <td>
                <table>
                  <tr>
                    <td>Bank</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td>{{ config('bank-accounts')[$order->bank]['bank'] }}</td>
                  </tr>
                  <tr>
                    <td>No.Rekening</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td>{{ config('bank-accounts')[$order->bank]['number'] }}</td>
                  </tr>
                  <tr>
                    <td>Atas Nama</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td>{{ config('bank-accounts')[$order->bank]['name'] }}</td>
                  </tr>
                  <tr>
                    <td>Total</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td>{{ number_format($order->total_payment) }}</td>
                  </tr>
                  <tr>
                    <td>Nama Pemesan</td>
                    <td>&nbsp;:&nbsp;</td>
                    <td>{{ $order->sender }}</td>
                  </tr>
                </table>
                  
                </td>
                <td>
                  @include('orders._details', compact('order'))
                </td>
              </tr>
            @empty
              <tr>
                <td colspan="4">Tidak ada order yang ditemukan</td>
              </tr>
            @endforelse
          </tbody>
        </table>
      </div>
      <a href="{{ url('/customers') }}">Kembali</a>
    </div>
  </div>
@endsection

resources/views/customer/view-orders.blade.php
@extends('layouts.shop')

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <table class="table table-hover responsive-table display" id="data-table-simple">
          <thead>
            <tr>
              <th>No. Order</th>
              <th>Tanggal Order</th>
              <th>Total</th>
              <th class="text-center" width="50">Konfirmasi</th>
              <th class="text-center">Status</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            @forelse($orders as $order)
            <tr>
              <td>{{ $order->padded_id }}</td>
              <td>{{ $order->created_at }}</td>
              <td>Rp{{ number_format($order->total_payment, 2) }}</td>
              {!! Form::model($order, ['route' => ['customers.update', $order], 'method' =>'patch', 'files' => true, 'class'=>'form-inline'])!!}
              <td>
                @if (isset($order) && $order->confirmation !== '')
                  <div class="thumbnail">
                    <img width="200" src="{{ url('/img/confirmation/' . $order->confirmation) }}" class="img-rounded">
                  </div>
                @else
                  <h4 class="text-center">Upload bukti pembayaran anda di sini</h4><br>
                @endif
                <p>{!! Form::file('confirmation') !!}</p>
                {!! Form::submit('Upload', ['class'=>'btn btn-primary btn-block']) !!}
                {!! $errors->first('confirmation', '<p class="help-block">:message</p>') !!}
              </td>
              {!! Form::close() !!}
              <td class="text-center"><strong>{{ $order->human_status }}</strong></td>
              <td><a class="btn btn-info" href="{{ route('customers.show', $order->id) }}">Lihat Detail</a></td>
            </tr>
            @empty
              <tr>
                <td colspan="4">Tidak ada order yang ditemukan</td>
              </tr>
            @endforelse
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection