app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/


Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/', 'CatalogsController@index');
    Route::get('/r', 'CatalogsController@r');
    Route::get('catalogs', 'CatalogsController@catalogs');
    Route::get('search', 'CatalogsController@search');
    Route::get('details/{id}', 'CatalogsController@details');
    Route::get('mail', 'UsersController@mail');
    Route::get('/home', 'HomeController@index');
    Route::resource('/customers', 'CustomersController', ['only' => [
        'index', 'show', 'update'
    ]]);
    
    Route::resource('categories', 'CategoriesController');
    Route::resource('products', 'ProductsController');
    Route::resource('users', 'UsersController');
    Route::resource('orders', 'OrdersController', ['only' => [
        'index', 'edit', 'update'
    ]]);

    Route::post('cart', 'CartController@addProduct');
    Route::get('cart', 'CartController@show');
    Route::delete('cart/{product_id}', 'CartController@removeProduct');
    Route::put('cart/{product_id}', 'CartController@changeQuantity');

    Route::get('checkout/login', 'CheckoutController@login');
    Route::post('checkout/login', 'CheckoutController@postLogin');
    Route::get('checkout/address', 'CheckoutController@address');
    Route::post('checkout/address', 'CheckoutController@postAddress');
    Route::get('checkout/payment', 'CheckoutController@payment');
    Route::post('checkout/payment', 'CheckoutController@postPayment');
    Route::get('checkout/success', 'CheckoutController@success');
});


Route::group(['middleware' => 'api'], function () {
    Route::get('address/regencies', 'AddressController@regencies');
});

resources/views/layouts/_customer-feature.blade.php
@can('customer-access')
  @include($partial_view, isset($data) ? $data : [])
@else
  @if (auth()->guest())
    @include($partial_view, isset($data) ? $data : [])
  @endif
@endcan

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Feloria.com</title>

    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel='stylesheet' type='text/css'>
    {{-- <link href="{{ url(elixir('css/app.css')) }}" rel="stylesheet"> --}}
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ url('plugins/data-tables/css/jquery.dataTables.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">

</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    Feloria.com
                </a>
                @include('layouts._customer-feature', 
                    ['partial_view'=>'catalogs._search-panel', 
                        'data'=>[
                                  'q' => isset($q) ? $q : null,
                                  'cat' => isset($cat) ? $cat : ''
                                ]
                    ])

                {{-- 
                @include('catalogs._search-panel', [
                  'q' => isset($q) ? $q : null,
                  'cat' => isset($cat) ? $cat : ''
                ]) --}}
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    {{-- @if(Auth::check()) --}}
                        @can('admin-access')
                            <li><a href="{{ url('/home') }}"><i class="fa fa-btn fa-home"></i>Home</a></li>
                            <li><a href="{{ route('categories.index') }}"><i class="fa fa-btn fa-tags"></i>Kategori</a></li>
                            <li><a href="{{ route('products.index') }}"><i class="fa fa-btn fa-gift"></i>Produk</a></li>
                            <li><a href="{{ route('orders.index') }}"><i class="fa fa-btn fa-shopping-cart"></i>Laporan</a></li>
                            <li><a href="{{ route('users.index') }}"><i class="fa fa-btn fa-gift"></i>Member</a></li>
                            
                        @endcan
                    {{-- @endif --}}
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">

                   @include('layouts._customer-feature', ['partial_view'=>'layouts._cart-menu-bar'])
                    
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        @include('layouts._customer-feature', 
                    ['partial_view'=>'layouts._check-order-menu-bar', 'data'=>[]])
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#"><i class="fa fa-btn fa-user"></i>Akun</a></li>
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @if (session()->has('flash_notification.message'))
        <div class="container">
            <div class="alert alert-{{ session()->get('flash_notification.level') }}">
                {{ session()->get('flash_notification.message') }}
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            </div>
        </div>
    @endif

    @yield('content')
    <hr width="85%">
    <div class="col-md-8 col-md-offset-1">&copy Feloria.com | Online Shop</div>

    <!-- JavaScripts -->
    {{-- <script src="{{ url(elixir('js/all.js')) }}"></script> --}}
    <script src="{{ asset('js/all.js') }}"></script>
    @if (Session::has('flash_product_name'))
        @include('catalogs._product-added', ['product_name' => Session::get('flash_product_name')])
    @endif

    <script type="text/javascript" src="{{ url('plugins/data-tables/js/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript" src="{{ url('plugins/data-tables/data-tables-script.js') }}"></script>
</body>
</html>

resources/views/layouts/shop.blade.php
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Feloria.com | Toko Online Peralatan Kantor Telengkap</title>
<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/bootstrap-select.css') }}">
<link href="{{ asset('css/shop-style.css') }}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{{ asset('css/flexslider.css') }}" type="text/css" media="screen" />
<link rel="stylesheet" href="{{ asset('css/font-awesome.min.css') }}" />
<link rel="stylesheet" href="{{ asset('css/sweetalert.css') }}" />
<link rel="stylesheet" href="{{ asset('css/selectize.bootstrap3.css') }}" />
<!-- for-mobile-apps -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Resale Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //for-mobile-apps -->
<!--fonts-->
<link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
<!--//fonts-->	
<!-- js -->
<script type="text/javascript" src="{{ asset('js/jquery.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/all.js') }}"></script>
<!-- js -->
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
<script src="{{ asset('js/bootstrap-select.js') }}"></script>
<script>
  $(document).ready(function () {
    var mySelect = $('#first-disabled2');

    $('#special').on('click', function () {
      mySelect.find('option:selected').prop('disabled', true);
      mySelect.selectpicker('refresh');
    });

    $('#special2').on('click', function () {
      mySelect.find('option:disabled').prop('disabled', false);
      mySelect.selectpicker('refresh');
    });

    $('#basic2').selectpicker({
      liveSearch: true,
      maxOptions: 1
    });
  });
</script>
@if (Session::has('flash_product_name'))
    @include('catalogs._product-added', ['product_name' => Session::get('flash_product_name')])
@endif
<script type="text/javascript" src="{{ asset('js/jquery.leanModal.min.js') }}"></script>
<link href="{{ asset('css/jquery.uls.css') }}" rel="stylesheet"/>
<link href="{{ asset('css/jquery.uls.grid.css') }}" rel="stylesheet"/>
<link href="{{ asset('css/jquery.uls.lcd.css') }}" rel="stylesheet"/>
<!-- Source -->
<script src="{{ asset('js/jquery.uls.data.js') }}"></script>
<script src="{{ asset('js/jquery.uls.data.utils.js') }}"></script>
<script src="{{ asset('js/jquery.uls.lcd.js') }}"></script>
<script src="{{ asset('js/jquery.uls.languagefilter.js') }}"></script>
<script src="{{ asset('js/jquery.uls.regionfilter.js') }}"></script>
<script src="{{ asset('js/jquery.uls.core.js') }}"></script>
<script>
	$( document ).ready( function() {
		
	} );
</script>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="logo">
				<a href="{{ url('/') }}"><span>Feloria</span>.com</a>
			</div>
			<div class="header-right">
				<span class="active uls-trigger"><a href="{{ url('/cart') }}"><i class="fa fa-shopping-cart"></i> {{ $cart->totalProduct() > 0 ? '(' . $cart->totalProduct() . ')' : ''}}</a></span>
				@if (Auth::guest())
					<span class="active uls-trigger"><a href="{{ url('/register') }}">Register</a></span>
                    <a class="account" style="margin-left: 10px" href="{{ url('/login') }}">Login</a>
                @else
                	<span class="active uls-trigger"><a href="{{ route('customers.index') }}">Cek Order</a>
					<div class="dropdown active uls-trigger" style="float:right">
					  <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					    {{ Auth::user()->name }}
					    <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
					    <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
					  </ul>
					</div>
                @endif
			</div>
		</div>
	</div>
	
	@yield('content');

	<!--footer section start-->		
	<footer>
		<div class="footer-top">
			<div class="container">
				<div class="foo-grids">
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Who We Are</h4>
						<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
						<p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
					</div>
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Help</h4>
						<ul>
							<li><a href="howitworks.html">How it Works</a></li>						
							<li><a href="sitemap.html">Sitemap</a></li>
							<li><a href="faq.html">Faq</a></li>
							<li><a href="feedback.html">Feedback</a></li>
							<li><a href="contact.html">Contact</a></li>
							<li><a href="typography.html">Shortcodes</a></li>
						</ul>
					</div>
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Information</h4>
						<ul>
							<li><a href="regions.html">Locations Map</a></li>	
							<li><a href="terms.html">Terms of Use</a></li>
							<li><a href="popular-search.html">Popular searches</a></li>	
							<li><a href="privacy.html">Privacy Policy</a></li>	
						</ul>
					</div>
					<div class="col-md-3 footer-grid">
						<h4 class="footer-head">Contact Us</h4>
						<span class="hq">Our headquarters</span>
						<address>
							<ul class="location">
								<li><span class="glyphicon glyphicon-map-marker"></span></li>
								<li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
								<div class="clearfix"></div>
							</ul>	
							<ul class="location">
								<li><span class="glyphicon glyphicon-earphone"></span></li>
								<li>+0 561 111 235</li>
								<div class="clearfix"></div>
							</ul>	
							<ul class="location">
								<li><span class="glyphicon glyphicon-envelope"></span></li>
								<li><a href="mailto:info@example.com">mail@example.com</a></li>
								<div class="clearfix"></div>
							</ul>						
						</address>
					</div>
					<div class="clearfix"></div>
				</div>						
			</div>	
		</div>	
		<div class="footer-bottom text-center">
		<div class="container">
			<div class="footer-logo">
				<a href="index.html"><span>Feloria</span>.com</a>
			</div>
			<div class="footer-social-icons">
				<ul>
					<li><a class="facebook" href="#"><span>Facebook</span></a></li>
					<li><a class="twitter" href="#"><span>Twitter</span></a></li>
					<li><a class="flickr" href="#"><span>Flickr</span></a></li>
					<li><a class="googleplus" href="#"><span>Google+</span></a></li>
					<li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
				</ul>
			</div>
			<div class="copyrights">
				<p> © 2017 Feloria.com All Rights Reserved | Design by  <a href="http://w3layouts.com/"> W3layouts</a></p>
			</div>
			<div class="clearfix"></div>
		</div>
	</div>
	</footer>
    <!--footer section end-->
</body>
</html>